version: '3'
services:
  workspace:
    build:
      context: ./workspace
      args:
        - TZ=${TZ}
    ports:
      - "4000:80"
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}